# Generated by Django 5.2.7 on 2025-10-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_addtocart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_image_code',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
