# Generated by Django 5.2.7 on 2025-10-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_product_ai_image_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ai_image_code',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
